#+title: Japan and Malaysia
#+subtitle: April 2023
#+setupfile: ../static/post.setup

#+begin_export html
<div id="flag">
<img src="../svg/japanmalaysia.svg">
</div>
#+end_export
 
* Mon, 10 April

14:14
Expected to arrive in KL at 8:30pm. Just passed Orange and expecting to fly through the centre of Australia, maybe past Broome. The land is divied up in polygons of contrasting colour, as far as I can see.

* Tue, 11 April

16:01
Early start this morning on about 5hours sleep on the second flight in from KL. We got into Kansai Osaka International airport at 6am and made out way straight to Universal Studios. Rides in order of favourite first:

1. Spiderman ride
2. Harry Potter ride (made Alex nauseous)
3. Jurassic Park ride
4. Mario Cart ride
5. Jaws ride

The structures in the park are amazing, particularly Super Mario World which covers horizon to horizon with so much colour and the Hogwarts buildings built on top of an artificial rocky hill.

Alex got really motion sick after the last ride of the day. It was a bit of a struggle getting back to our first AirBNB in town but made it in the end. Public transport is really good and easy. Feels like we're staying in the back streets of Osaka.

Impressive feat of the day: watching a school girl wedge through a sea of people to get from the middle of the metro car to the exit. So much polite confidence and precision.

21:11
Tried to go to a vegan/vegetarian okonomiyaki (pancake) place for dinner. Ended up with ticket 17. The couple with ticket 6 had been waiting for 2 hours so we abandoned. We explored Dotonburri before settling some rice balls and onigiri from the convenience store next to our accommodation. Back was very tight this evening. 25,206 steps says Garmin.

* Wed, 12 April

15:32
Breakfast at Mercy Vegan. To get there we walked through a park and said hi to some little friendly doggoes. We both had plant based egg sandwiches, Alex's coffee (long black with some plant milk) was nutty, fragrant and tasty.

Caught the subway to Osaka castle and explored the area. We also visited the Porco mall (10 storey mall) for a desert style taro bao and to browse Tokyu Hands store. Picked up some sushi fridge magnets and a pen that writes good. After we found a cool little restaurant for some vegan curry served with rice, miso soup and a salad.

The rain had begun by the time we left the restaurant and we had a 2km walk back to accom ahead of us. Took a photo of rainy Dotonburri canal in the rain. Just drying off and taking a stretch and rest before attempt 2 at okonomiyaki for dinner.

Cultural exchange of the day: the waitress at Mercy cafe was interested in how long we'd been vegan. She had been for 6 years and one of the pastry chefs had been for 2 years. She mentioned that it's hard to be vegan in Japan, which is easy to see.

21:36
We arrived at OKO 15 minutes and lined up before opening and got the last available table. The restaurant was very small and the one staff did everything herself (cook, serve, take payment, organise the queues). We had some gyoza entree and then shared a vegan okonomiyaki (pancake). Oijii.  After dinner we took the subway to explore Shinsekai. Spotted some cool indoor archery ranges, themed and styled restaurants, and arcade games.

* Thu, 13 April

14:06
Left Osaka this morning and arrived in Kyoto around 9am. We stored our bags in a locker and went straight to the Fushimi Inari Temple, taking a walk surrounded by orange gates. After the walk we travelled into the city for some lunch at a restaurant specialising in sesame. Alex had a sesame noodle curry and I had a rice curry, yum. Then to Kyoto station to catch the Shinkansen to Odawara, then Gora (Hakume).

The Shinkansen was cool, very fast, quiet and comfortable. Way better than flying. We got off at Odawara and caught a little twin caboose up the mountain valley into Gora. The train had to perform a few switchbacks with the train driver switching ends, and the atmosphere was really cool chugging up the tracks through trees lines, tunnels and cool views.

20:15
We arrived in Gora and organised a corner store dinner (onigiri, noodles, edamame and some snacks). Not much is open on Gora on a Thursday, so hopefully we can find some more food tomorrow.

Saw a lot of tourists today in Kyoto, and a lot of luggage. Glad we packed light and figured out our ICOCA cards to skip the ticket lines.

Sight of the day: on the train up to Gora we spotted some firefighters(?) scrambling attached into a cable between two little towers (4ish storeys). Seems like they were training. Closely followed by the crowd gathered to photograph the cat waiting at the corner store door (he didn't go in when the door was opened but looked like he wanted to).

Snacks of the day: Warabimochi, powdered fern root on sweet soya bean powder. Fried peanut snacks.

21:21
It's very quiet here. In contrast to Osaka where the streets were busy and bustling constantly, here the streets are back alleys and walkways. The roads nearby are sleeping with rarely a car.

Garmin step count: 18,799

* Fri, 14 April

20:37
Big day today. Left around 9am and just got back (8:30pm). We didn't start with a solid plan for the day, but it worked out great;
1. Caught the cable train up the hill to Sounzan Station
2. Caught the Hakone Ropeway (cable car) to Togendai. We had a cool view of Mt Fuji 🗻 and of the sulfur springs on the way
3. Caught the Hakone Pirate Ship to Motohakone
4. Grabbed a convenience store lunch
5. Walked the Old Tokaido Road Ancient Cedar Avenue walk (by accident)
6. Walked the Old Hakone Highway, stopping for Amazake (sweet fermented rice drink served warm) on the way (super tasty). The Highway was partially old large cobbles and very scenic. There were some other hikers but it was a very quiet track.
7. Caught the bus back to Hakone-Yumoto Station
8. Walked up to Hakone Yuryo onsen and managed to convince the concierge to allow us into a private Onsen. The onsen was booked for two hours which we spent nearly all of there
9. Caught the shuttle back to Hakone-Yumoto, too late for dinner so another convenience store meal and then caught the train back to Gora to our accommodation

Phrase of the day: Green tea vibes, overheard from the group of Americans at a vending machine.

Garmin score: 20,439

* Sat, 15 April

21:48
We had a lazy morning waking up around 8, packing and leaving a bit before 10 to travel the trains to Yakohama. Learnt that the train between Gora and Hakone-Yumoto is the second steepest track in the world.

Yakohama was super busy, big and hard to navigate. We found a bag locker and then met up with Miyuki and baby Aoto for lunch. She took us to a fancy shabu shabu (hot pot) restaurant and then to a small shop to get us a gift (soba set).

After Yakohama we caught the train into Shinjuku Tokyo to check in at the hotel (floor 30 of 30; great view) and head straight back out for dinner at a close by vegan place that was alright. On the way back we made a detour to wander through Omide Yokocho, a little alley with dozens of crammed restaurants. Really cool old school Japanese. Then stopped at a bar (Yona Yona Beer Works) for a drink.

Next to our hotel, the Tokyu Kabukicho Tower (225m, 48 storey building) had just opened (14th) and they were hosting a Blue Festival. The lower floors are all open to the public (restaurants, arcade, cinema, etc.) so we went in for an explore. Took escalators up to level 10, also bought a Kabuki mug from a cinema gift shop.

Play of the Day: there was a guy in a bunch of FC Tokyo gear at Yona Yona Beer Works, and the staff bought out a t-shirt for him to sign (which already had a bunch of other signatures, presumably notable patrons). Bit of a brush with fame.

Garmin leaderboard: 15,354

* Sun, 16 April

16:22
This morning started with a walk to Shinjuku Gyoen. We spent some time walking around the gardens and appreciating the interesting trees. The cherry blossom had just finished but a few of the trees were still blooming. From there we walked to Meiji Jingu (shrine). The shrine and surrounding buildings were intricate timber; very impressive. Then to lunch at vegan bistro Jangara for some spicy ramen (and garlic oil ramen for Alex). Best meal of the trip!

We walked down the crowded Harijuku (which is famous for cosplay shops), and then caught the train to Shibuya. At Shibuya we took a photo of the famous dog, walked across the scammble, found a lookout of the scammble, did a bit of tidbit shopping (mechanical pencil and chopsticks) at Today's Special, and found the station Eki Stampu for Alex's book.

19:36
We went to a tempura fast food chain for dinner and had some tempura veggies, before heading back to the hotel the long way through a bunch of shops (stationary shop, homeware shop, Disney store, Muji). Tomorrow we head to KL.

Close call of the day: at Meiji Jingu a group of tourists had found the Stampu and were debating whether to put it on their passport. They saw Alex in line and asked. When Alex said she wouldn't and explained her stamp book one said: "the only one with common sense is the stranger". They had a laugh at themselves.

Garmin count: 25,456 (new record)

* Mon, 17 April

20:42
Travel day from Tokyo to KL. Left and caught the Skyliner to Narita airport and jumped on the plane. Alex left her passport in the back seat pocket of the plane so after changing terminals on the bus we had to do a bit of a scramble to get it back, all good in the end.

After jumping off the plane we caught the KLIA Ekspres train into Sentral and then train to near our hotel. The train ticket was a little blue plastic coin, pretty interesting. Then a muggy walk for about 15 minutes through the back streets. Lots of noise, sound and smells to take in. The hotel isn't up to Alex's standards, but you get what you pay for ($28).

We're having a cup noodle dinner using the chopsticks we bought in Japan and then off to bed.

* Tue, 18 April

22:10
This morning we went out to find some roti and daal. The place we were going was closed because it's currently Ramadan which a lady across the street explained to us, and suggested another spot. At this new spot, at a cart on a side alley we ate for about 50c each.

Then time to check out and head to Alex's uncle's law firm (Kong Hock). He brought Alex her dad's watches and then took us to the apartment. We got the aircon up and running and once they left the apartment needed a bit of a clean up, mostly cockroach droppings.

Late lunch we headed to a nearby mall and did some grocery shopping on the way back. A bit more cleaning and then cooked up some air fryer curry puffs and salad for dinner. After dinner we did some exploring of the building (Aria) to find the pool, spa, saunas, gym, observation deck, etc.

The heat here is heavy, the outside is noisy and smelly. It's an interesting place to be. Kinda glad to be out of that last hotel though honestly.

* Wed, 19 April

14:22
KL, the city of malls, the city of 40-50 storey apartment blocks under construction, the city of security guards. This morning we went for a walk to a nearby garden to have a look which turned into a full morning event. After the park we went into the mall at the base of the Petronas towers and through the Petrosains Science Discovery Centre (KL's Questacon). Even though we were the only ones there without kids or parents it was awesome. My favourite was the F1 racing simulator (force feedback wheel and bumping chair). After that we did a bit of mall jumping to get to Minf Houze vegan for some Nasi Lemak (and Hainanese chicken for Alex). On the way back we grabbed some potato curry puffs and cockroach spray.

21:00
After some sorting of Foo's stuff and cockroach fumigating we walked I to town again for dinner. Found a vegetarian Nasi Lemak place. Once we got back we had a nice long swim in the apartment pool, a quick go of the jacuzzi and a sauna attempt (under maintenance). Used the free wifi to download a movie on Netflix and going to watch on a bit of a bodge monitor/soundbar/phone setup.

Malls visited: 5

Steps: 20,347

* Thu, 20 April

17:15
This morning was a bit of a slow start as we waited for a quick storm to pass through, but we went to to top floor to have a look around in the drizzle. We caught the train to Kampung Baru, but the next one to Batu Caves was over 30 minutes wait so we downloaded Grab (Uber) and got a lift there, paying in cash (cool app).

Batu Caves was really cool. Heaps of monkeys, pigeons and chickens roaming around. The caves were impressive, as was the Lord Muragan statue and painted rainbow stairs. At the base Alex was forced to cover up her knees so we were given a 15 ringit sari.

After having a look around we caught the train back into town and had lunch at Kusa Vegan Japanese. Tasty sushi tray, hand rolls and lemon kombucha. Then for a wander around one of the malls exploring the Japanese shop area and a few other stalls. After getting home we had a quick dip in the pool to relative the humidity, although the morning rain made today feel much more comfortable (even though the weather has it around 30 degrees).

21:16
Walked into the first restaurant we went to after we arrived for some Nasi Lemak and a caramel mylk Boba (curry ramen for Alex). Afterward we did a bit of fancy brand watch window shopping before wandering home.
 
Play of the day: there's a 4 way traffic light with no pedestrian lights near the apartment that we cross often (maybe 4 or 5 times so far). We have to time the car lights to get across safely. Starting to get so good at it that other people have been following our lead.

Garmin score: 22,879

* Fri, 21 April

19:11
This morning Alex was on a call with the family to tour the apartment and go through items they wanted, so we started the days adventures at lunch. Caught a Grab to KL city centre and had lunch at a Chinese no meat restaurant. Very good crunchy wings which had a fake bone (cut wooden chopsticks). After lunch we explored the markets on Petaling Street and then walked to Merdeka Square to take a few pics. Then down to the National Mosque and onto mini Stonehenge. At the time the weather app was saying 33, feels like 41, and we were struggling.

Rehydrated with a slushie and chrysanthemum tea at the bird park and then went in for a look. It was cool to see the birds: peacocks, owls, ibis, parrots, hornbill, pelican, ostrich, emu, and more. One of the coolest was the African Grey Parrot copying other bird sounds. It did feel a little cruel though, felt a bit overpopulated and some birds looked agitated in the smaller non open areas. Then caught a Grab back to Kusa and had some ramen (2/5 spice but I struggled, probably pranked).

On the way home we got some mango gelato, stopped by an art supply store to get a cardboard tube for the artwork (ended up being too small), and briskly walking back in the rain trying to keep the tube dry. Once back we jumped straight in the pool, and then quickly out once the lightning storm began. Writing this from the pool area in the storm. Tomorrow's our last day. I'm looking forward to being home again, but I'll miss this place and this trip.

22:20
Fireworks everywhere tonight. It must be the official Hari Riya. Awesome view from up here on level 25 above the golf course.

Garmin counter: 16,741

* Sat, 22 April

14:55
Last day in KL today, we leave before dinner for our flight. First thing was to start packing. We've been packing artwork, Foo's crazy watch collection, fancy pens and little sculptures. The large painted art at the front door we were hoping to unframed and put in a packing tube, but after pulling it apart we found it was glued onto the timber backing, so it's going to have to stay unfortunately. Also unfortunate that we broke the frame glass getting it out (but there wasn't really another way).

Before lunch we went for a last swim in the pool and then caught a Grab out to Chinatown. Ate at The Hungry Tapir, best Nasi Lemak yet and Alex got some Truffle infused mac'n'cheese. We had a Pandan cake as well (reminds Alex of childhood).

Just arrived back in the apartment so time to finish packing, clean up and say goodbye to KL.

19:50
On the KL Ekspres to the airport now. Going to be a long night of travel, arriving back in Sydney at 10am tomorrow. Liz (L12) has offered to pick us up from the airport which is a lifesaver. We've packed everything up, sitting probably a bit too heavy on our bags but let's pray for mercy at the hands of the airliners. It was hard for Alex to leave the apartment, but hopefully will bring some closure for the family. We were very lucky to have this opportunity and grateful to Kong Hock for arranging access to the apartment for us.
