#+title: Melbourne and Great Ocean Road
#+subtitle: April 2024
#+setupfile: ../static/post.setup

#+begin_export html
<div id="flag">
<img src="../svg/australia.svg">
</div>
#+end_export
 
* Sunday 16 April

21:15
Surge have just won Div 2 nationals in Shepparton with Alex coaching and myself coming 13th with Kronk (seed 20/24). Very successful tournament and awesome journey for the women.
After the tournament we travelled to Melbourne and had an awesome vegan pub meal at The Cornish Arms. Thankful to be on holiday and not making a late trip back to Wollongong.

https://live.staticflickr.com/65535/53676808486_056f0fd3d8_k.jpg

* Monday 17 April

20:10
After late breakfast at a cafe we left for Aireys Inlet stopping in Torquay along the way. We visited the Australian Surf Museum and then stopped at Bells Beach for a look. Waves down this way are amazing, super clean sets and turquoise blue water. We arrived at Sunnymead hotel and had a scrumptious pizza and focaccia at Captains of Aireys.

https://live.staticflickr.com/65535/53677262610_5fe32adb7e_k.jpg

https://live.staticflickr.com/65535/53677027863_5639009d60_k.jpg

* Tuesday 16 April

18:12
Tuesday spa day. Before the spa we went for a look at the lighthouse and a quick walk on the beach before heading back to Sunnymead. The spa day had us in a private steam room (vishy) with some exfoliation and clay stuff to rub on and a shower for 30 minutes. That was followed by a 60 minute couples massage and then a little grazing platter with some chai tea.


https://live.staticflickr.com/65535/53677262605_8de82f7b86_k.jpg


In the afternoon we drove to Lorne for a couple of waterfalls. First Erskine falls, really nice and just a short steep walk for the carpark. We then stopped at Sheoak picnic area for a 4km there and back tramp to see Henderson and Won Wondah Falls.

https://live.staticflickr.com/65535/53675934057_608c6a5703_k.jpg

https://live.staticflickr.com/65535/53677262495_b8715d0855_k.jpg

* Wednesday 17 April

21:43
We left Aireys Inlet and travelled the Great Ocean Road all the way to Port Campbell stopping along the way:
- Apollo Bay for a vege pastie for lunch
- Gibsons steps
- Twelve Apostles
- London Bridge
- Bay of Martyrs 
- Bay of Islands

https://live.staticflickr.com/65535/53677163364_260f7baa2a_k.jpg
  
The weather has been overcast and windy with some rain so the oceans have been a bit choppy. The Apostles was packed with tourists and we enjoyed the other queiter stops more. We've seen evidence of penguins at London Bridge beach so planning to head back at dusk for a sighting. We also saw a Bandicoot at the Bay of Martyrs lookout on the path. Finished the day hanging at the London Bridge lookout from sunset till the light disappeared. Right at the end we thought we caught a sight of the penguins but it was too dark to confirm. Stayed the night at a brewery guesthouse (Sow and Piglets) in Port Campbell.

https://live.staticflickr.com/65535/53675933947_7e9de798b4_k.jpg

* Thursday 18 April

17:50
We left Port Campbell and made our way to Separation Creek via:
- Triplet Falls, awesome easy 1 hour loop through forest with heaps of tree ferns. The first two lookouts were overgrown but the third was good.
- Hopetoun falls, steep little 15 min return track to the falls. Best falls of the trip.
- The Redwoods, we arrived here and had a wander through the trees. Smells so good.
- Koala walk at Skenes Creek, we saw three koalas mostly sleeping.
Stayed the night with Maddie and Tom in Tom's family holiday house.

https://live.staticflickr.com/65535/53677163284_16ef18395c_k.jpg

https://live.staticflickr.com/65535/53677262390_fd35cce1a9_k.jpg

* Friday 19 April

20:54
In the morning we had a walk on the beach with Maddie and I jumped in for a cold swim. Water was super rough so I wasn't in for long. We left before lunch to arrive in Collingwood for check-in to our hotel. We had lunch at a vegan deli (Smith Deli), highlight was the tuna melt toastie. From there we walked around Collingwood visiting the Purebaby outlet, Patagoo outlet and Bonds Outlet stores. In the evening we caught the tram into the Convention Centre to watch the BBC Earth Experience (doco projected on a bunch of screens around a big exhibition room) which was a really cool and relaxing time. We trammed back to Collingwood and had some Arancini and Pizza at Red Sparrow Pizza.

https://live.staticflickr.com/65535/53677262330_74a299970c_k.jpg

* Saturday 20 April

9:30
Cheeky lunch at Smith Deli again and now it's time to drive back home.
