#+title: Switzerland and France
#+subtitle: December 2025
#+setupfile: ../static/post.setup

#+begin_export html
<div id="flag">
<img src="../svg/switzerlandfrance.svg">
</div>
#+end_export
 
* Itinerary
Winterthur 🚆-> Rapperswil 🚆-> Lucerne 🚆-> Interlaken (+Grindelwald) 🚆-> Geneve 🚆-> Lyon 🚗-> Avignon 🚗🚆-> Montreux 🚆-> Bern 🚆-> Winterthur (+St Gallen)

* Mon, 22 Dec

18:39
After a 9 hour flight to Bangkok then 12 hours to Zurich, Celia met us at the airport at 7am to catch the train to their house in Winterthur (Florastrasse 21, 8400 Winterthur, Switzerland). Although cramped for space on the plane, Ayla did quite well.

After a delicious breaky of fruit, bread and crossaunt we got prepared for a walk, rugging up the babies in their prams. Mina and Ayla fell asleep along the river before we headed for the old town. In Winterthur the Christmas markets were running and we picked up some warm roasted chestnuts (Marroni).

After the temperature dropped we headed to the supermarket (Migros) for some nappies and then home. Celia made a Zurich traditional creamy mushroom pasta and Mina and Ayla had a good play before bed. James fell asleep by accident on the couch and we will probably be in bed by 7:30.

https://live.staticflickr.com/65535/55047434280_456848e2d7_b.jpg

* Tue, 23 Dec

22:09
After a big sleep in we had an easy morning. Celia went in to pick up her sister Milena, Alex watched the girls and James went for a walk to the recycling bin station and supermarket recycling.

After lunch we took a trip to Zurich with Celia and Mina. First we stopped at Stadelhofen Christmas markets so Mina could ride the carousel while we checked out the Christmas tree and stalls. Then we walked to the singing Christmas Tree carols and Ayla fell asleep. On the way there we passed all of the Swiss watch boutiques and stars were hung in the air between all of the buildings.

The carols were very crowded so we went to the currency museum and got some Hot Swiss Mule (wine) before heading home. For dinner dean and Celia made us Raclette.

https://live.staticflickr.com/65535/55047279223_089346638e_b.jpg

* Wed, 24 Dec

21:35
Today we celebrated Christmas with Celia's dad's family in their apartment. We had a nice sleep in and then Dean and Mina took us out so that Celia and Milena could prepare. We went the the post office, then had a light buffet breaky at Tibits, before stopping in to the store and the  heading back. On the way back there was some light snow.

The afternoon was spent eating delicious food and opening secret Santa gifts before a big cleanup.

https://live.staticflickr.com/65535/55047434175_172c846baa_b.jpg

* Thu, 25 Dec

19:55
Today we had an easy morning and stroll around Winterthur before heading to Rapperswil-Jona (Celia's home town) to Angela's house (Celia's mum) arriving early evening. Her side is Italian and we had a delicious vegan lasagna Christmas dinner and only ended up in bed at 11pm.

https://live.staticflickr.com/65535/55047356659_d292354807_b.jpg

* Fri, 26 Dec

19:51
This morning we slept in and had a nice long breaky/brunch before heading for a long walk. We went up past the school and around down a scenic route taking us to the castle. We had a look in the church (at the organ) and then had a play on the playground which had a wicked slide that Ayla and Mina loved taking turns on.

Next to the castle and playground was a deer sanctuary, set up by the king after the queen was taken by a deer to see their fawns and she asked that they stop hunting them.

After that we headed to the train station where Manfred delivered our luggage by car and we left for Lucern. We checked into our hotel (The Lubo) in the old town and then went for a quick dinner and grocery shop before packing in for the night.

https://live.staticflickr.com/65535/55047434240_f83b6ab41b_b.jpg

* Sat, 27 Dec

21:19
This morning we were singing "No more monkeys, jumping on the bed", but Ayla's version is "No monkey bed!"

After having some breaky we went for a quick shop for lunch and made sandwiches then headed (by about 12) to Pilatus. The trip was just over an hour: a bus, then a 4 person gondola 🚡, then to the peak a 55 person gondola 🚠. The first gondola got us over the cloud line to see the sun the first time this trip as it's been overcast every day.

The peak at Pilatus was amazing. We could view all the surrounding Alps over the clouds and the air was crystal clear. We spent a while up there eating some lunch then wandering around and taking plenty of photos.

Ayla note: we took her in the carrier up which was good as it was quite crowded in some parts and we didn't have to worry about stairs (at the peak). We also would've had to squish it into the 4 person gondola.

We had dinner at Tibits, a vegetarian restaurant chain in Switzerland that makes cozy homemade buffet pay by weight food.

https://live.staticflickr.com/65535/55047356559_fb8d00c1ae_b.jpg

https://live.staticflickr.com/65535/55046196192_fec6896746_b.jpg

* Sun, 28 Dec

19:07
Today we went on a self guided walking tour of Lucerne. Some of the highlights were: 
- the massive cantilever on the exhibition Centre
- the Lucern lion 🦁 carved into the cliff
- the timber bridges over the river
- the churches were grand and we went to one where the organ was playing
- the city wall was cool

Ayla loved the lion. Alex liked the water in the river which was super clear and blue-green and I was actually in awe of the cantilever. The walk took up the whole day (11ish - 5ish) and afterwards we grabbed some groceries and food from veganitas to eat back at the hotel.

https://live.staticflickr.com/65535/55047434170_26a21052cf_b.jpg

* Mon, 29 Jan
 
19:36
Today we packed the bags and visited a few shops quickly. Alex bought a Santa tree decoration and I bought some Victorinox nail clippers as gifts. We then grabbed a vegan schnitzel sub from Twiny before boarding the train to Interlaken. Pro tip, get on the right side for the best views.

After checking in we wandered around town for a bit and got Ayla some snow mittens since we lost one of the pair Celia lent us. Even with the eternal fog we could see the cliffs surrounding the city and they look incredible.

We had a booking at Fondue Villa and had vegan fondue and chocolate fondue for dessert. Alex's favourite was the capsicum in cheese, my favourite was the bread or the capsicum, but the surprise was the pineapple which was actually a top pick. Ayla just liked the plain bread.

Note: in Interlaken there was a city bus that played a super loud clown Horn at a person walking on the street. The bus had a Horn painted on it's side. We also saw an electric bus charging at a bus bay.

Ayla note: when we put mittens on Ayla likes to say "nip nip" with the associated action.

https://live.staticflickr.com/65535/55047091091_cb8e038794_b.jpg

* Tue, 30 Dec

21:09
Today was Jungfroujock day. We travelled to "The top of Europe" by catching the train from Interlaken to Grindelwald, then the ski Gondola up to Eigergletcher, then the cogwheel train up to Jungfraujoch. 

We did the discovery loop which included an elevator up to the observation deck (-10 degrees outside), then the ice palace (ice cave with ice carvings), then outside to view the mountains.

It took a while to get used to the altitude, but we were rewarded with some incredible views and landscape. On the way down we hoped out at Eigergletcher to walk on the snow, take some photos, and watch some skiers head off before making our descent back to Interlaken.

Ayla note: Ayla loved the "ice blocks" (walls of the ice palace) and tickled them ("tickle tickle").

https://live.staticflickr.com/65535/55047433905_bf81b0738f_b.jpg

https://live.staticflickr.com/65535/55047091001_c47cd89c00_b.jpg

https://live.staticflickr.com/65535/55046196082_28eef79bab_b.jpg

* Wed, 31 Dec

13:36
We started the day with a train ride to Grindelwald and explored the ski village a bit before taking the most rickety 4 person gondola 🚡 part way up the hill to Bort where we had a picnic lunch and a long play at the playground.

19:55
We then took the Bort-Muhlebach hike down the hills to some stunning scenery. We had to take care on some of the roads where the snow had turned icy. The 1 hour walk took us 2 since we kept getting lost, and spent most of the time rerouting but made it in the end. Then the bus back to Grindelwald and the train back to Interlaken for dinner.

Happy New Year! (the new year in Aus ticked by at 2pm here)

https://live.staticflickr.com/65535/55047090891_aa2de0c8e2_b.jpg

https://live.staticflickr.com/65535/55046195987_abae744c5b_b.jpg

https://live.staticflickr.com/65535/55046195752_57088c7fc0_b.jpg

* Thu, 1 Jan 

18:54
After a hotel breaky we did a quick Migros shop for lunch and caught the train to Geneve. After checking in we went for a walk to the old town, stopping by the flower clock ⌚, then through the old town to St Pier cathedral.

We had a delicious dinner at Pasta People (Alex had spicy arabiata and Ayla and myself had Pesto) and theb Ayla thoroughly enjoyed a ride on the carousel before we walked home for the evening.

https://live.staticflickr.com/65535/55047355849_be5fd12a28_b.jpg

https://live.staticflickr.com/65535/55047278403_4f5de825a7_b.jpg

https://live.staticflickr.com/65535/55047355889_8cc2bc5de1_b.jpg

https://live.staticflickr.com/65535/55047355819_6b7e1000f1_b.jpg

* Fri, 2 Jan

21:07
Today we had a quick supermarket lunch before heading to the Geneve Botanic Gardens for a quick wander and a look at the animals. We left a bit late and nearly missed the train back to the hotel, but got back in time to grab the bags and hop on the train to Lyon.

Our Hotel (Bayard Bellacor) is a super old and fancy place. We ended up upgrading to get a bigger room which is lucky as our room would've been pretty small. We went for a walk while Ayla slept but struggled to find any dinner as all kitchens are closed until 7pm. Had to make do with a supermarket breaky. Hopefully we will have more luck tomorrow.

The old parts of Lyon are pretty and the city feels a lot bigger than what we've gotten used to. It's also much more grungy than Switzerland.

* Sat, 3 Jan

18:57
Big day on Lyon today, from Bellacour we went north for breaky/brunch at Zeitgeist (a vegan restaurant) where we had crossaunt with tofu scramble, sweet potato tartine, and French toast with pecan and vanilla creme. Then we walked past Fontaine Bartholdi and the Ampitheatre des Trois Gaules (not super well upkept section of very old steps). Then we stopped at Voi, a vegan Patisserie for some pastries and a coffee for Alex and a self dubbed "Ayla-chino".

From there we walked to the Parc de la Tete d'Or while Ayla slept. We had a look at the Botanic gardens (lots of Aussie plants in the greenhouses) and sat to eat our pastries. When Ayla woke we went to the zoo section and saw some monkeys, a tapir, flamingoes, ducks in frozen water and giraffes.

From there we walked to the metro station to the funicular up to the Basilique Notre-Dame
de Fourvière and the Théâtre Gallo Romain which was pretty impressive, but by now we were all getting cold so hit the funicular and metro back to Bellacour.

Back at Bellacour before turning in we had a ride on the Ferris Wheel (my first one maybe and Ayla's first one). Then back to the hotel for a rest and then (at the 7pm kitchen open) some takeaway ramen to eat back at the room.

https://live.staticflickr.com/65535/55047433430_74aee01695_b.jpg

https://live.staticflickr.com/65535/55047433455_5ce2245ab6_b.jpg

* Sun, 4 Jan

18:15
We had an easy morning today before heading to breakfast at Newtree (big bowl or soy yoghurt with a mueslie/nut/fruit buffet and a hot chocolate). Ayla enjoyed her babychino. We then quickly packed our bags and caught the metro out to Part-Dieu where we picked up our hire car.

They didn't have a car seat so they unpacked a brand new one (for 0-15 month olds) which Ayla fit luckily. Alex did a great job driving from Lyon to Avingnon where we joined Aurelie, Chris and Tillie at the airBnB for the next few days. We went for a quick walk through town seeing the old papal residence and some left over Christmas settings.

https://live.staticflickr.com/65535/55046195432_0943d184c5_b.jpg

https://live.staticflickr.com/65535/55047090526_982bb2daa3_b.jpg

* Mon, 5 Jan

20:05
Today we walked into town in Avignon and did a tour of the old papal residence. It was very old and big. They ran some art exhibits there which in some cases ruined the old vibe but a lot of the original furnishings were missing anyway.

When the girls fell asleep we came back to hang at the airBnB and have a baguette and toppings lunch.

In the evening we drove out to the Aquaduc at Pont du Gard. Super cool and old. We got there just as the sun went down which made for some cool but rushed photos.

https://live.staticflickr.com/65535/55046195347_bc6cc24c7f_b.jpg

https://live.staticflickr.com/65535/55047090246_89d2dcfb13_b.jpg

* Tue, 6 Jan

21:15
Big day today. We drove from Avingnon to Arles and had a quick bite before walking through the local (still in use) Arenes de'Arles and the Arles Ampitheatre.

From Arles we went to the Ornitolgical Park of Pont de Gau where we saw heaps of Flamingos 🦩, a Heron and an otter (maybe, or another water mamal). The area was swampy and some of the water had frozen over so the birds were mostly grouped in one area.

Note: flamingoes are a bit ugly, not what I thought, even if very interesting. There were also a lot of horses in the area, this area is know for a particular white breed.

One the way home we stopped at Aigues-Mortes, a small pretty city surrounded by a grand wall. It was beautiful but we only stayed briefly (picked up some salts as gifts) as it was getting late. Back home now for some home cooked dal masala and late bed for the kids.

https://live.staticflickr.com/65535/55047090336_bd3c4d4ca5_b.jpg

https://live.staticflickr.com/65535/55047090451_a6ce71859f_b.jpg

https://live.staticflickr.com/65535/55047432995_eb3cc8d5f9_b.jpg

* Wed, 7 Jan

17:39
Today we drove to see the markets in Saint-Remy-de-Provance. They seemed a bit quiet (maybe because of the cold) but there was one amazing olive and dip stall that I bought some olives from. We had some lunch at a cafe (Honore) and they let us into their second room that had a kids play area which they loved.

Then we went to the Carrières des Lumières where they played a light show in the quarry called The Little Prince. Really cool and Ayla and Tillie enjoyed running around inside. The landscape was really cool with rocky hills. We visited the village on top of the hill (Chateau des Baux-de-Provence) for some photos and wandered the streets before the drive home.

https://live.staticflickr.com/65535/55047277768_c835e8945e_b.jpg

https://live.staticflickr.com/65535/55046194882_0c4798d104_b.jpg

https://live.staticflickr.com/65535/55047277663_b58bc0192e_b.jpg

* Thu, 8 Jan

22:31
Thought this would be a boring journal note today, but we had a little plot twist at the end. Travel from Avingnon to Montreax. As we drove from Avingnon there was some rain and the closer we got to Lyon the more snow appeared. This also cause heavy congestion and our 2.5 hour drive was nearly 4 hours getting us to Lyon only 20 minutes before the train. Luckily we made it. Then we arrived at Geneve, grabbed some food and boarded the train to Montreax.

Somewhere around halfway (at the Renens stop) I had a weird feeling and checked the nappy bag stored above us which was gone. We searched the carriage and looked around but it seems someone stole it. It was full of Ayla's stuff but also had our passports along with cards and drivers licences.

The train officers directed us to do a police report and when we arrived in Montreax we went to the station. At the moment we have left our details with police and train officers in case it shows up but haven't submitted a formal notice as it will cancel our passports. If it isn't found by Sunday we'll make a report and will have to go to Geneve to get new passports. Big bummer, but at the moment we just have fingers crossed the bag will be found.

https://live.staticflickr.com/65535/55047089906_622c6428aa_b.jpg

* Fri, 9 Jan

20:32
Today we had a fairly slow morning. We went for a walk along the lake to the Migros supermarket to restock some baby supplies and get some supermarket breaky which we ate back at the Hotel Mona common area downstairs.

Around midday we left for the aquarium at Lausanne. On the way I got an email that our passports were found in Rorschach (but not the bag unfortunately). The aquarium was really cool and Ayla enjoyed looking at the ceiling exhibits (or just herself) in the floor mirror tiles. Highlights were the crocs, the big tanks with big fish and the Amazon room. Aylas highlight was probably the snakes.

We grabbed tomorrow's breaky at the Lausanne Tibits takeaway and then trained back to Montreux where we had dinner at an Italian restaurant with Mandy and Tom before coming back for a bath and bed.

Ayla note: when we saw the baby snake Ayla said "licking" because it was flicking it's tongue.
 
https://live.staticflickr.com/65535/55047355349_924ef51545_b.jpg

* Sat, 10 Jan

15:35
Easy morning again today. We had some breakfast in the room and then caught the train to Vevey before noon. We walked around the markets and then the old town. At the markets we were offered a free falafel and Ayla liked it so we went back and bought a handfull to snack on.

After a quick trip to the mall to get a new silicone bib we had lunch from Bretzelkonig (smokey planted rolls) and then went up the funicular to Mont Pelerin. Up the top was a thick layer of snow, we only stayed for 15 minutes but Ayla had a good time playing with it and the views were awesome.

Back in the hotel now and we are getting ready for Dean and Celia's reception at Fairmont Le Montreux Palace.

https://live.staticflickr.com/65535/55047089951_22a48de31a_b.jpg

https://live.staticflickr.com/65535/55046194782_79dabca32f_b.jpg

23:45
Super fun reception. They had a live salsa band and we, including Ayla, did some salsa all night. The babysitters were funny, Ayla wasn't happy to be left alone and I rescued an escaped kid early in the evening, haha.

https://live.staticflickr.com/65535/55047355084_94dbd291b4_b.jpg

https://live.staticflickr.com/65535/55047089866_c5e557f23e_b.jpg

* Sun, 11 Jan

16:17
Last minute decision today we decided to attempt to sled 🛷 before heading to Bern. After packing all the bags, storing them at the hotel, and having breaky we caught the train to Vevey and then the cogwheel ⚙️ train to Les Pleiades. Unfortunately no rentals there so we snow hiked down to Lally and found the kids hill but didn't have any cash so missed out on a kid sled hire. Ayla still had a great time playing in the thick snow and a good nap during the hike. Pretty magical place in the snow up there. With hindsight we would have gone up the funicular from Montreux but we were told it could be too dangerous for the bub.

Now on our way to Bern. We split up so Alex and Ayla could get Tibits at Lausanne before they close for late lunch and I could go collect the bags from Montreux. We'll meet at Lausanne station then be on our way to Bern.

https://live.staticflickr.com/65535/55047355099_45c2326e41_b.jpg

https://live.staticflickr.com/65535/55047089801_01c37910e0_b.jpg

* Mon, 12 Jan

20:23
Today was one of the best days we've had, so awesome. We started the day with some breaky from a vegan bakery (called Bakery Bakery). We had two different hot pastries, a quiche and a gipfeli for (Ayla) later. Then we wandered the old town seeing the Zytglogge (mechanical astronomical clock), Berner Munster (cathedral), Bern Munsterplatform, BarenPark (although nothing to see as bears were hybernating), and Parliment house (which had an outdoor I've skating rink out the front.

We grabbed some takeaway tuny sandwiches on the way to the tram for lunch and then caught the funicular up to the local hill (Gurten). Up there was snow and we hired a sled 🛷 to use on the slopes. Ayla had a fun few goes and then wasn't so sure but we had a great time sledging. The views up there were so nice.

We came back down and went to Tibits for dinner before heading over to the ice skating ⛸️. Ayla could site in a little pusher and she loved it. Then she loved hoping out and pushing it around the rink. We lost track of time but I think we were there from 6:30 to 8:00. So much fun.

Note: the Bern old town is the best so far. Very big and the details in the buildings are so intricate and old. There is some super impressive retaining walls as well.

https://live.staticflickr.com/65535/55047089776_dd8eac1a40_b.jpg

https://live.staticflickr.com/65535/55047354999_2c1f73d5e8_b.jpg

https://live.staticflickr.com/65535/55047089746_aa0d910032_b.jpg

https://live.staticflickr.com/65535/55047354939_358427ff72_b.jpg

https://live.staticflickr.com/65535/55047432495_cfdcc4255b_b.jpg

https://live.staticflickr.com/65535/55047277208_ecd97657ab_b.jpg

* Tue, 13 Jan

17:02
Today was a travel day. We ran a bit late this morning, but had some Tibits for breaky before catching the train to Winterthur. We dropped out luggage at Dean and Celia's place then grabbed lunch to go at Bakery Bakery. Then train to Rorschach where we picked up our passports (had to pay a 75CHF fee for them). Very glad to have these back.

We had a look at the lake near the train station then caught a train to St Gallen where we spent some time wandering the old town. Alex also got her train stamp. Now we are on the train back to Winterthur. Alex is planning to cook up a birthday dinner when we get back and then we'll hopefully have a nice early night.

Note: St Gallen seemed to have the most smokers per m² out of all the places we've been. Nearly impossible to get a breath of fresh air in the streets.

https://live.staticflickr.com/65535/55047089596_9c49735f8d_b.jpg

https://live.staticflickr.com/65535/55047277133_1e0e577b2b_b.jpg

https://live.staticflickr.com/65535/55047277143_5e43f23944_b.jpg

* Wed, 14 Jan

22:10
Last day today. We did a day trip to Zurich. We ate lunch at Hitl (oldest vegetarian restaurant still in operation), wandered the old town, bought some souvenirs (cow for Alex's mum, Victorinox stuff for Alex's family, and Alex got me a super tinker Swiss army knife for my birthday). We also had a mega swing session that Ayla loved. Grabbed some thankyou presents for Dean and Celia on the way back and made some pasta for dinner.

https://live.staticflickr.com/65535/55047354744_ffe99ed087_b.jpg

https://live.staticflickr.com/65535/55046194472_c5f7acb536_b.jpg

* Thu, 15 Jan

06:59 (Bangkok time)
Boarding the flight home today after one last bread and gipifli breakfast. We walked to the train 🚆 station in Winterthur which is 15min from Zurich airport and we were on our way.

https://live.staticflickr.com/65535/55046194307_bccba780d3_b.jpg

* People
- *Carlos* - Celia's dad with Columbian background
- *Patricia* - Celia's aunt who was very nice to us
- *Frank* - Patricia's "toy boy" gave us some tips and what to expect with our itinerary. Had some good insights into the mystery of Swiss German language
- *Angela* - Celia's mum with Italian background, she made us a specific tomato and eggplant vegan lasagna for Christmas dinner (best lasagne I've ever had) and hosted us in her house (in her master bedroom) while she and her partner stayed in a hotel
- *Gabriela and Lutz* - Dean and Celia's neighbours/landlords. Very nice to us and helped us with the spare key when we stayed on the way home
- *Milena* - Celia's vegan/no-fruit sister. Super nice and stayed with us over Christmas 
- *Pascuali* - Celia's grandad, gave Ayla a toy deer at the reception. Didn't seem to speak much English but very friendly

